### ISSUE TITLE
Video's not working

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#596] opened 2018-06-14 12:04 UTC
Error reported in course PythonSummerPrep on page intro-VariablesExpressionsandStatements by user Anzhelika k.anzhelika18@gmail.com
My video is not working, I cannot watch it.

**Comment by bnmnetp** [comment] 2018-06-15 12:27
duplicate of a duplicate of a known problem.  Working on the YouTube migration.

**Closed** 2018-06-15 12:27 UTC
