### ISSUE TITLE
Can't delete programming item from an assignment

### ISSUE THREAD

**Issue by cigas** [RunestoneInteractive/RunestoneComponents#433] opened 2017-08-15 16:53 UTC
![twoproblems](https://user-images.githubusercontent.com/11619455/29327621-65526ff4-81b5-11e7-9fe9-b00b91d4036b.PNG)
![oneproblemtosolve](https://user-images.githubusercontent.com/11619455/29327628-69b6a0a6-81b5-11e7-88ad-a54122222d25.PNG)

I created a new assignment at runestone.academy in the course CigasTest. I added two reading components, then added two programming components by using the search feature, then clicking on the "Add to Assignment" button. This works as I expected. 

However, I cannot use the X button to delete any of the programming components. 

The X button does delete the reading components.

Something happened, because one of the problems is somewhat deleted, in that I can't solve it when I view the actual Assignment, but  it still appears in the list of items when I edit the assignment from the instructor's page.

**Comment by bnmnetp** [comment] 2017-08-16 14:50
Yep, there's something going on with adding from search...  The person I need to look at that is on vacation.  However, as a workaround, if you refresh the page, you should be able to delete.  At least I was when I reproduced your problem.

@bjones1 -- It appears that updateAssignmentRaw is not correctly connecting this question to the picker tree.   My hunch is that it is again related to how the ids are constructed for the tree versus how the ids are stored in the rest of the database.

**Comment by cigas** [comment] 2017-08-16 18:08
I see you were able to delete the items. I put them back, but even after a page refresh, I can't get rid of them. I've tried in a couple of different browsers as well, in case that made a difference.

**Comment by bjones1** [comment] 2017-08-19 02:57
A couple of quick thoughts before I'm actually back and can work on  this:

- Are the problematic questions being added by searching for them, or from the tree? I assume the first.
- Are the problematic questions user-created exercises, or content that already exists in the course?

That will at least give me a bit of background to look at possible problems. `updateAssignmentRaw` make the assumption that the question already exists in the tree picker. When the user adds a question, this is an incorrect assumption. Is this also incorrect on user-created exercises found via search? If so, we'll need similar code to add the question to the tree picker.

**Comment by bnmnetp** [comment] 2017-08-20 19:16
Yes, searching and adding.  I can reproduce this by searching for and choosing an existing Exercise , then clicking on the Add to Assignment button.  If I immediately click on the button to remove it nothing happens.  For me, if I reload the page, then the remove button works.

**Comment by cigas** [comment] 2017-08-20 20:41
OK, I was finally able to delete after refreshing, but only for some questions. I can't delete any questions that have those null fields.

**Comment by bnmnetp** [comment] 2019-09-13 21:22
@bjones1 Did you ever get a chance to try to dig into this?  I poked at it today -- as I was fixing the bug with adding sub-chapters and problems in the right order!! 🎉 RunestoneInteractive/RunestoneServer#1336

It looks to me like sometimes -- after searching for a question for example the function to delete a row of the table just isn't wired to that row.  As clicking on the x to delete a question has no effect, that is no functions are called!  This is fixed by refreshing the page.

Stranger however is the problem that @tluchko where even a page refresh leaves the question stuck on the assignment no matter what.

**Comment by bnmnetp** [comment] 2019-09-13 21:23
@tluchko -- I removed your problem question manually.

**Comment by tluchko** [comment] 2019-09-13 22:04
Great.  Thank you.

**Comment by bjones1** [comment] 2019-09-13 22:32
I remember writing some rather complicated work-around for this when it was first raised, but I don't even remember what I did at this point.

**Comment by cigas** [comment] 2020-01-14 04:43
I ran into this again today in course CS152HOSP2020, Assignment: Day 01- Readings. 
I had copied all the assignments from CS152HOSP2019 (Thanks for this feature!!!), but forgot that this assignment contained a bunch of unwanted programming exercises as well. I was able to delete most of them (150 ish), but none of the assignments starting with rab_...
Refresh didn't do any good.
I don't know how the exercises got there in the first place - it was a mistake.
At this point, I'm not sure these exercises are still available. When I try to search for exercises starting with rab..., I don't see any of the ones in my assignment.

**Comment by bnmnetp** [comment] 2020-01-15 00:29
I have removed the rab_ questions from your "Day 01 - Readings" assignment.  I think they may have gotten in before some loopholes were closed.  I'm just not sure...

If you run into others please let me know.  In the meantime I'll try to track down why the delete doesn't seem to work there.

**Comment by bnmnetp** [comment] 2020-01-15 00:38
Update:  I don't knowhow they got there, but I do understand why the delete doesn't work.

The table is supposed to represent things that appear in the tree view, and so when you click the X in the table the javascript tries to uncheck the question in the tree.  The rab_ questions got into the assignment, but they are private questions, so they don't appear in the tree!  Hence the removal fails.

@bjones1 I know its been a while, but I think we ought to come up with a more robust way of removing questions from the table view.  I'm guessing we could do more around 489 of admin.js

**Comment by cigas** [comment] 2020-01-15 00:57
Thanks for the removal. I still don't remember what exactly I did, but I imagine it was something like adding ALL the exercises for a chapter at once. I'd guess that the exercises were public at one point, but then set to private later, after they were already part of my assignment.

**Comment by bnmnetp** [comment] 2020-01-15 00:58
Yeah, at one point last semester I added a dialog so that if you check the exercises section it will pop up and say "you are about to add 242 questions to your assignment are you sure?"

**Comment by bjones1** [comment] 2020-01-15 23:01
@bnmnetp, it looks like you've already taken care of this in a01806cc6047de23bde872b425ca6b702775b1ed. Your fix there looks great to me. Thanks!

**Closed** 2020-02-04 00:45 UTC
