### ISSUE TITLE
Difficult Page Navigation

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#304] opened 2016-11-13 11:55 UTC
Error reported in course thinkcspy on page FlowofExecutionSummary by user anonymous anonymous
I love interactivepython, however on my iPad I find page navigation difficult. I have to click the tiny page arrows a few times to get to the previous or next page. I would suggest changing the navigation to this format http://chimera.labs.oreilly.com/books/1230000000393/index.html
Thanks.

**Comment by bnmnetp** [comment] 2017-07-05 19:39
duplicate of #12

**Closed by bnmnetp** 2017-07-05 19:39 UTC
Labels: more info needed
