### ISSUE TITLE
Skip

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#538] opened 2018-01-21 19:04 UTC
Error reported in course UNCcs301 on page /runestone/assignments/doAssignment?assignment_id=1516 by user sova4698 sova4698@bears.unco.edu
Please describe what you were doing that led up to this error:

---------------- Traceback --------------
Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/assignments.py", line 1346, in <module>
  File "/home/bmiller/Runestone/web2py/gluon/globals.py", line 409, in <lambda>
    self._caller = lambda f: f()
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/assignments.py", line 1257, in doAssignment
    logger.debug("user_id = %s labels[chapters] = %s labels[sub_chapters] = %s",auth.user.id,labels['chapters'].chapter_label,labels['sub_chapters'].sub_chapter_label)
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by bnmnetp** [comment] 2018-01-23 15:22
duplicate of RunestoneInteractive/rs#191 and RunestoneInteractive/RunestoneComponents#541

**Closed by bnmnetp** 2018-01-23 15:22 UTC
