### ISSUE TITLE
Tried to delete a course and got this window.

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#625] opened 2018-07-05 17:04 UTC
Error reported in course DSA501-A&DS on page /runestone/default/removecourse/DSA501-A&DS by user carbonjo carbonjo@buffalostate.edu
Please describe what you were doing that led up to this error:

---------------- Traceback --------------
Traceback (most recent call last):
  File "/home/bmiller/Runestone/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/default.py", line 394, in <module>
  File "/home/bmiller/Runestone/web2py/gluon/globals.py", line 409, in <lambda>
    self._caller = lambda f: f()
  File "/home/bmiller/Runestone/web2py/gluon/tools.py", line 3964, in f
    return action(*a, **b)
  File "/home/bmiller/Runestone/web2py/applications/runestone/controllers/default.py", line 299, in removecourse
    db((db.user_courses.user_id == auth.user.id) & (db.user_courses.course_id == course_id_query[0].id)).delete()
  File "/home/bmiller/Runestone/web2py/gluon/packages/dal/pydal/objects.py", line 2702, in __getitem__
    row = self.records[i]
IndexError: list index out of range

**Comment by bnmnetp** [comment] 2018-07-05 18:31
duplicate of #619

**Closed by bnmnetp** 2018-07-05 18:31 UTC
