### ISSUE TITLE
Audio Muted for Videos

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#519] opened 2017-12-20 16:55 UTC
Error reported in course thinkcspy on page OrderofOperations by user PythonIsFun jyoung@jewellinstruments.com
Whenever I try to watch  videos the audio is muted and I cannot hear it.

**Comment by bnmnetp** [comment] 2017-12-20 17:08
Duplicate of RunestoneInteractive/rs#200

**Closed by bnmnetp** 2017-12-20 17:08 UTC
