### ISSUE TITLE
site bug

### ISSUE THREAD

**Issue by irunestone** [RunestoneInteractive/RunestoneComponents#873] opened 2019-08-10 07:58 UTC
Error reported in course fopp on page scaffolded_code by user -dead-inside- bro.mad2016@yandex.ru
1) At post project questions if you choose some answer multiple times it will look like "Thanks, your response has been recordedThanks, your response has been recordedThanks, your response has been recorded..."

2) Seems like common problem on this website. The progress looks like "You have attempted 10 of 11 activities on this page", with only 10 activities.

**Comment by bnmnetp** [comment] 2019-08-10 19:01
Number 2 is not a bug.  The "extra" activity is opening the page.

**Comment by alexmojaki** [comment] 2019-10-05 17:58
I see the page at https://runestone.academy/runestone/books/published/fopp/Projects/scaffolded_code.html but I don't see it anywhere in https://github.com/RunestoneInteractive/fopp. Is the published book significantly different to the master branch on fopp?

**Comment by alexmojaki** [comment] 2019-10-05 17:59
Also I can't see how to reproduce point 1, can anyone else?

**Comment by bnmnetp** [comment] 2019-10-05 18:07
The published book uses the ac101 branch. — this is so that multiple authors can remix or use the master according to their own strategies.  Right now there are two books that are descendents of master.

I fixed 1 some time ago, but apparently should have closed this issue.

**Closed by bnmnetp** 2019-10-05 18:07 UTC
Labels: bug, good first issue
